server:
  port: 8095

spring:
  application:
    name: auth-service
  
  # 允许Bean定义覆盖
  main:
    allow-bean-definition-overriding: true
  
  # 配置多数据源
  datasource:
    # 禁用默认数据源自动配置
    type: com.zaxxer.hikari.HikariDataSource
    # 自定义数据源配置由DataSourceConfig类处理
    mysql:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/graduateemploymentinfo?useUnicode=true&characterEncoding=utf8
      username: root
      password: 238373
      jdbc-url: jdbc:mysql://localhost:3306/graduateemploymentinfo?useUnicode=true&characterEncoding=utf8
    postgresql:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/interview
      username: 238373
      password: 
      jdbc-url: jdbc:postgresql://localhost:5432/interview
  
  # Redis配置
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 10000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0

# JWT配置
jwt:
  secret: eAf6XIz7Q6CmE3N4K5L6M7N8O9P0Q1R2S3T4U5V6W7X8Y9Z0aBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz
  expiration: 86400000  # 24小时，单位毫秒
  header: Authorization
  token-prefix: Bearer 

# 日志配置
logging:
  level:
    com.employment.auth: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO 