spring:
  mail:
    protocol: smtp                   # 邮件协议
    host: smtp.qq.com                # smtp 服务器地址 （163邮箱为例）
    port: 587                        # 端口号（163邮箱为例）
    username: 2383731319@qq.com           # 发送人邮箱地址
    password: qkurpqhkilbqdigf          # 授权码
    default-encoding: utf-8          # 编码字符集
    debug: true                      # 开启debug模式用户会完整打印邮件发送过程的日志

  datasource:
    url: jdbc:postgresql://localhost:5432/interview
    username: lqy0584
    password: 
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-init-sql: "CREATE EXTENSION IF NOT EXISTS vector;"
  ai:
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        initializeSchema: false
        dimensions: 1536
        schemaName: public
        tableName: vector_store
        batching-strategy: TOKEN_COUNT # Optional: Controls how documents are batched for embedding
        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch

# 添加auth-service配置
auth:
  service:
    url: http://localhost:8095  # auth-service服务地址
  token:
    secret: ${AUTH_TOKEN_SECRET:your-secret-key}  # JWT密钥，建议通过环境变量配置