spring:
  mvc:
    static-path-pattern: /static/**
  aop:
    proxy-target-class: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/graduateemploymentinfo?useUnicode=true&characterEncoding=utf8
      username: root
      password: Liu050804
      filter: stat,wall,log4j
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 2000
      pool-prepared-statements: false
      max-open-prepared-statements: -1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  main:
    allow-bean-definition-overriding: true
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.gr.geias.model
  type-handlers-package: com.gr.geias.handler
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
    use-column-label: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com:
      gr:
        geias:
          repository: debug
server:
  port: 8080

# 添加面试API配置
employment:
  api:
    key: ${EMPLOYMENT_API_KEY:ai-interview-secret-key}  # API密钥，建议通过环境变量配置

# JWT配置
jwt:
  secret: eAf6XIz7Q6CmE3N4K5L6M7N8O9P0Q1R2S3T4U5V6W7X8Y9Z0aBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz
  expiration: 86400000  # 24小时，单位毫秒
  header: Authorization
  token-prefix: Bearer 

# AI面试系统API配置
ai-interview:
  api:
    url: http://localhost:8088  # AI面试系统API地址
    token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInN1YiI6ImFkbWluIiwidXNlclR5cGUiOjIsImV4cCI6MTcyMTk2NTQ5MH0.AXCTmPqQZ_Aw-BLjV9Hs1GzPuJkA5-3zxjxrKMnQ9Eo  # 使用与auth-service相同密钥签名的JWT令牌

# 爬虫服务配置
crawler:
  url: http://localhost:8000  # 爬虫服务URL

pagehelper:
  helper-dialect: postgresql
  reasonable: true
  support-methods-arguments: true 